<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rijwan" failures="1" tests="2" name="Maven1.Project1.TestCase14_rating" time="33.241" errors="0" timestamp="2025-05-08T00:45:38 IST" skipped="1">
  <testcase classname="Maven1.Project1.TestCase14_rating" name="rating" time="13.520">
    <failure message="expected [null] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [null] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1079)
at org.testng.Assert.assertEquals(Assert.java:1119)
at Maven1.Project1.TestCase14_rating.rating(TestCase14_rating.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Test Started: rating
TestCase is Failed]]>
    </system-out>
  </testcase> <!-- rating -->
  <testcase classname="Maven1.Project1.TestCase14_rating" name="rating" time="19.721">
    <skipped/>
    <system-out>
      <![CDATA[Test Started: rating]]>
    </system-out>
  </testcase> <!-- rating -->
  <system-out>
    <![CDATA[Test Started: rating
Test Started: rating
TestCase is Failed
Test Started: register
TestCase is Passed
Test Started: validatePaymentMethodSelection
Test Started: validatePaymentMethodSelection
TestCase is Failed
Test Started: reachcartwithoutlogin
TestCase is Passed
Test Started: addProductToCart
Test Started: addProductToCart
TestCase is Failed
Test Started: searchwithfilters
Test Started: searchwithfilters
TestCase is Failed
Test Started: failedLogin
Test Started: failedLogin
TestCase is Failed
Test Started: sortProductsByRelevancePriceRating
Test Started: sortProductsByRelevancePriceRating
TestCase is Failed
Test Started: verifyProductDetails
TestCase is Failed
Test Started: validateCompleteCheckoutProcess
TestCase is Failed
Test Started: updateAndRemoveItemsFromCart
Test Started: updateAndRemoveItemsFromCart
TestCase is Failed
Test Started: validateCouponCodeApplication
Test Started: validateCouponCodeApplication
TestCase is Failed
Test Started: profileupdate
TestCase is Passed
Test Started: loginandsearch
TestCase is Passed
Test Started: login
TestCase is Passed]]>
  </system-out>
</testsuite> <!-- Maven1.Project1.TestCase14_rating -->
